# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Configuration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(734, 439)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.gridLayout_4 = QtWidgets.QGridLayout(Form)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 5, 6, 1, 1)
        self.ThresholdVelocity = QtWidgets.QLabel(Form)
        self.ThresholdVelocity.setStyleSheet("color: rgb(255, 255, 255);")
        self.ThresholdVelocity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ThresholdVelocity.setObjectName("ThresholdVelocity")
        self.gridLayout_3.addWidget(self.ThresholdVelocity, 2, 1, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 7, 1, 1)
        self.MovementSensLabel = QtWidgets.QLineEdit(Form)
        self.MovementSensLabel.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"border-radius: 11px;")
        self.MovementSensLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.MovementSensLabel.setObjectName("MovementSensLabel")
        self.gridLayout_3.addWidget(self.MovementSensLabel, 4, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 4, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 3, 6, 1, 1)
        self.ActivitiesLabel = QtWidgets.QLineEdit(Form)
        self.ActivitiesLabel.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"border-radius: 11px;")
        self.ActivitiesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ActivitiesLabel.setObjectName("ActivitiesLabel")
        self.gridLayout_3.addWidget(self.ActivitiesLabel, 0, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 2, 8, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 4, 0, 1, 1)
        self.StudyID = QtWidgets.QLabel(Form)
        self.StudyID.setStyleSheet("color: rgb(255, 255, 255);")
        self.StudyID.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StudyID.setObjectName("StudyID")
        self.gridLayout_3.addWidget(self.StudyID, 5, 1, 1, 3)
        self.StudyIDLabel = QtWidgets.QLineEdit(Form)
        self.StudyIDLabel.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"border-radius: 11px;")
        self.StudyIDLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.StudyIDLabel.setObjectName("StudyIDLabel")
        self.gridLayout_3.addWidget(self.StudyIDLabel, 5, 5, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem6, 0, 6, 1, 1)
        self.Prompts = QtWidgets.QLabel(Form)
        self.Prompts.setStyleSheet("color: rgb(255, 255, 255);")
        self.Prompts.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Prompts.setObjectName("Prompts")
        self.gridLayout_3.addWidget(self.Prompts, 1, 3, 1, 1)
        self.ThresholdSteps = QtWidgets.QLabel(Form)
        self.ThresholdSteps.setStyleSheet("color: rgb(255, 255, 255);")
        self.ThresholdSteps.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ThresholdSteps.setObjectName("ThresholdSteps")
        self.gridLayout_3.addWidget(self.ThresholdSteps, 3, 1, 1, 3)
        self.ThreshVelLabel = QtWidgets.QLineEdit(Form)
        self.ThreshVelLabel.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"border-radius: 11px;")
        self.ThreshVelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ThreshVelLabel.setObjectName("ThreshVelLabel")
        self.gridLayout_3.addWidget(self.ThreshVelLabel, 2, 5, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem7, 0, 2, 1, 1)
        self.ThreshStepsLabel = QtWidgets.QLineEdit(Form)
        self.ThreshStepsLabel.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"border-radius: 11px;")
        self.ThreshStepsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.ThreshStepsLabel.setObjectName("ThreshStepsLabel")
        self.gridLayout_3.addWidget(self.ThreshStepsLabel, 3, 5, 1, 1)
        self.PromptsLabel = QtWidgets.QLineEdit(Form)
        self.PromptsLabel.setStyleSheet("background-color: rgb(209, 209, 209);\n"
"border-radius: 11px;")
        self.PromptsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PromptsLabel.setObjectName("PromptsLabel")
        self.gridLayout_3.addWidget(self.PromptsLabel, 1, 5, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem8, 1, 2, 1, 1)
        self.MovementSens = QtWidgets.QLabel(Form)
        self.MovementSens.setStyleSheet("color: rgb(255, 255, 255);")
        self.MovementSens.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.MovementSens.setObjectName("MovementSens")
        self.gridLayout_3.addWidget(self.MovementSens, 4, 1, 1, 3)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem9, 3, 0, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem10, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 5, 0, 1, 1)
        self.Activities = QtWidgets.QLabel(Form)
        self.Activities.setStyleSheet("color: rgb(255, 255, 255);")
        self.Activities.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Activities.setObjectName("Activities")
        self.gridLayout_3.addWidget(self.Activities, 0, 3, 1, 1)
        self.SaveTxt = QtWidgets.QPushButton(Form)
        self.SaveTxt.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(61, 217, 245, 255), stop:1 rgba(240, 53, 218, 255));\n"
"font: 9pt \"Microsoft YaHei UI\";\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius: 15px;")
        self.SaveTxt.setObjectName("SaveTxt")
        self.gridLayout_3.addWidget(self.SaveTxt, 6, 3, 1, 1)
        self.MainMenuBtn = QtWidgets.QPushButton(Form)
        self.MainMenuBtn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(61, 217, 245, 255), stop:1 rgba(240, 53, 218, 255));\n"
"font: 9pt \"Microsoft YaHei UI\";\n"
"color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-radius: 15px;")
        self.MainMenuBtn.setObjectName("MainMenuBtn")
        self.gridLayout_3.addWidget(self.MainMenuBtn, 6, 5, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem12, 6, 6, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 6, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Configuration"))
        self.ThresholdVelocity.setText(_translate("Form", "Threshold for velocity measurement"))
        self.StudyID.setText(_translate("Form", "Study ID"))
        self.Prompts.setText(_translate("Form", "Prompts Generated"))
        self.ThresholdSteps.setText(_translate("Form", "Threshold for Steps in a day"))
        self.MovementSens.setText(_translate("Form", "Sensitivity of movement detected"))
        self.Activities.setText(_translate("Form", "Number of Activities"))
        self.SaveTxt.setText(_translate("Form", "Save as text file"))
        self.MainMenuBtn.setText(_translate("Form", "Main Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
